development:
  adapter: postgresql
  encoding: unicode
  database: blocipedia-starter_development
  pool: 5
  username: sashafklein
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: blocipedia-starter_test
  pool: 5
  username: sashafklein
  password: